name: banking4students
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  fl_chart: ^0.70.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  flutter_svg: ^2.0.17
  cloud_firestore: ^5.6.5
  provider: ^6.1.2
  firebase_storage: ^12.4.4
  image_picker: ^1.1.2
  rxdart: ^0.28.0
  http: ^1.3.0
  google_fonts: ^6.2.1
  flutter_check_box_rounded: ^3.3.0
  floating_bottom_bar: ^0.0.3
  graphic: ^2.5.1
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.1
  lottie: ^3.3.1
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_name:
  name: "UniFinance"

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/icon/app_icon_trans.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/achievements_svgs/
    - lib/assets/Flags/
    - lib/assets/onboarding/
    - lib/assets/onboarding/animation1.json
    - lib/assets/onboarding/animation2.json
    - lib/assets/onboarding/animation3.json
    - lib/assets/onboarding/app_icon_anim.json
    - lib/assets/icon/app_icon_anim.gif
    - lib/assets/ai_agent/bg1.jpg
    - lib/assets/ai_agent/bg2.jpg
    - lib/assets/ai_agent/bg3.jpg
    - lib/assets/ai_agent/bg4.jpg
    - lib/assets/ai_agent/bg5.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
