// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoiIEAzHURk0jRyDAarIDlg29XnvHY6zw',
    appId: '1:838608860208:web:939425fa07d631107aa9f5',
    messagingSenderId: '838608860208',
    projectId: 'banking4students-32a97',
    authDomain: 'banking4students-32a97.firebaseapp.com',
    storageBucket: 'banking4students-32a97.firebasestorage.app',
    measurementId: 'G-FLHLXNTKF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1E0HyY1xPHVvVCzpLWMvWvaZveCt_EGo',
    appId: '1:838608860208:android:bc89a8a1b15fa7527aa9f5',
    messagingSenderId: '838608860208',
    projectId: 'banking4students-32a97',
    storageBucket: 'banking4students-32a97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYQIGnCub4J72AodJ6IJgzLfyHyXXrRYs',
    appId: '1:838608860208:ios:736f00a58e750b687aa9f5',
    messagingSenderId: '838608860208',
    projectId: 'banking4students-32a97',
    storageBucket: 'banking4students-32a97.firebasestorage.app',
    iosBundleId: 'com.example.banking4students',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYQIGnCub4J72AodJ6IJgzLfyHyXXrRYs',
    appId: '1:838608860208:ios:736f00a58e750b687aa9f5',
    messagingSenderId: '838608860208',
    projectId: 'banking4students-32a97',
    storageBucket: 'banking4students-32a97.firebasestorage.app',
    iosBundleId: 'com.example.banking4students',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoiIEAzHURk0jRyDAarIDlg29XnvHY6zw',
    appId: '1:838608860208:web:5cdb0d09da2af05d7aa9f5',
    messagingSenderId: '838608860208',
    projectId: 'banking4students-32a97',
    authDomain: 'banking4students-32a97.firebaseapp.com',
    storageBucket: 'banking4students-32a97.firebasestorage.app',
    measurementId: 'G-J2V7RVMTB9',
  );
}
